version: '3.8'
services:
  app:
    container_name: laravel
    build: .
    command: 'php artisan serve --host=0.0.0.0'
    volumes:
      - .:/app
    ports:
      - 8000:8000
  cron:
    container_name: cron
    build: ./cron
    volumes:
      - .:/app
